bbs/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from blog import views
from django.views.static import serve
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('logout/', views.logout),
    path('reg/', views.register),
    path('index/', views.index),
    #将所有以blog开头的，都交给blog里的url来处理
    path('blog/', include("blog.urls")),
    path('get_valid_img/', views.get_valid_img),
    # path('reg/', views.reg),
    #极验滑动验证码，获取验证码的url
    path('pc-geetest/register', views.get_geetest),
    #用来校验用户名是否被注册
    path('check_username_exist/', views.check_username_exist),
    #设置media的路由
    re_path("media/(?P<path>.*)$",serve,{"document_root": settings.MEDIA_ROOT}),

    path('upload/', views.upload),

]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class UserInfo(AbstractUser):

    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11,null=True,unique=True)
    avatar = models.FileField(upload_to="avatars/",default="avatars/default.png",verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog",to_field="nid",null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

class Blog(models.Model):

    nid =models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  #个人博客标题
    site = models.CharField(max_length=32,unique=True)  #个人博客后缀
    theme = models.CharField(max_length=32) #博客主题

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name

class Category(models.Model):

    nid = models.AutoField(primary_key = True)
    title = models.CharField(max_length=32)  #分类标题
    blog = models.ForeignKey(to = "Blog",to_field="nid",on_delete=models.CASCADE)  #外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name

class Tag(models.Model):
    nid = models.AutoField(primary_key = True)
    title = models.CharField(max_length=32)  #标签名
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE) #所属博客

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name



class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50) #文章标题
    desc = models.CharField(max_length=255)  #文章描述
    create_time = models.DateTimeField(auto_now_add=True) #创建时间
    comment_count = models.IntegerField(verbose_name="评论数",default=0)  #评论数
    up_count = models.IntegerField(verbose_name="点赞数",default=0)
    down_count = models.IntegerField(verbose_name="踩数",default=0)


    category = models.ForeignKey(to = "Category",to_field="nid",null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(to = "UserInfo",to_field="nid",on_delete=models.CASCADE)
    tag = models.ManyToManyField(  #中介类型
        to = "Tag",
        through="Article2Tag",
        through_fields=("article","tag")  #注意顺序！！！
            )

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

class ArticleDetail(models.Model):
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article =models.OneToOneField(to="Article",to_field="nid",on_delete=models.CASCADE)

    def __str__(self):
        return self.article.title

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name

class Article2Tag(models.Model):
    # 文章和标签的多对多关系表
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid",on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}".format(self.article.title,self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)  # 联合唯一
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", null=True,on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    def __str__(self):
        return self.user

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name

class Comment(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    content = models.CharField(max_length=255)    #评论内容
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    parent_comment = models.ForeignKey("self",null=True,on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

blog/forms.py
# bbs 用到的fomr类

from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from blog import models
#定义一个注册的form类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label = "用户名:",
        error_messages = {
            "max_length":"用户名最长16位",
            "required":"用户名不能为空",
        },
        widget = forms.widgets.TextInput(
            attrs={"class":"form-control"}
        )
    )
    password = forms.CharField(
        min_length=6,
        label = "密码",
        widget= forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        ),
        error_messages = {
        "min_length": "密码最少要6位",
        "required": "密码不能为空",
    }
    )
    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        error_messages={

            "required": "确认密码不能为空",
        },
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value = True
        )
    )
    email = forms.EmailField(
        label="邮箱",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"}
        ),
        error_messages = {
        "invalid": "邮箱格式错误！",
         "required": "邮箱不能为空"
    }
    )
    # 重写username字段的局部钩子
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 表示用户已经注册
           self.add_error("username",ValidationError("用户名已经存在"))
        else:
            return username

            # 重写email字段的局部钩子

    def clean_email(self):
        email = self.cleaned_data.get("email")
        is_exist = models.UserInfo.objects.filter(email=email)
        if is_exist:
            # 表示用户已经注册
            self.add_error("email", ValidationError("邮箱已经存在"))
        else:
            return email

    #重写全局的钩子函数，对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if re_password and re_password != password:
            self.add_error("re_password",ValidationError("两次密码不一致"))
        else:
            return self.cleaned_data

templates/Login2.html
<!DOCTYPE html>
{#使用极验验证码的登录页面#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-quiv="x-ua-compatible" content="IE=edge">
{#    <meta name="viewport" content="width=device-width,intial-scale=1">#}
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <title>Title</title>
</head>
<body>
<h3>登录页面</h3>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="">用户名</label>
                    <input type="text" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="text" class="form-control" id="pwd">
                </div>
                <div class="form-group">
                   {#  放置极验验证码#}
                        <div id="popup-captcha"></div>
                        </div>
                        <input type="button" class="btn btn-primary pull-right login_btn" value="登录">
                        <span class="error"></span>
            </form>
        </div>
    </div>
</div>


{#bootstrap,js#}

<script src="/static/jquery/jquery-3.4.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
{#引入了封装failback的接口 initgeetest#}
<script src="/static/gt.js"></script>


<script>
    //极验发送登录数据的
    var handlerPopup = function (captchaObj) {
        captchaObj.onSuccess(function () {
            var validate = captchaObj.getValidate();
            $.ajax({
                url: "/login/",
                type: "post",
                dataType: "json",
                data: {
                    username: $('#username').val(),
                    password: $('#pwd').val(),
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode,
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                },
                success: function (response) {
                    console.log(response);
                if (response.status) {
                    //登录成功
                    location.href = "/index/";
                } else {
                    //登录失败
                    $(".error").html(response.msg).css("color", "red");
                }
                }
            });
        });
        $(".login_btn").click(function () {
            captchaObj.show();
        });
        // 将验证码加到id为captcha的元素里
        captchaObj.appendTo("#popup-captcha");
    };
    //当Input框获取焦点时，将之前的错误清空
    $("#username,#pwd").focus(function(){
            $(".error").text("")
    })



    // 验证开始需要向网站主后台获取id，challenge，success（是否启用failback）
    $.ajax({
        url: "/pc-geetest/register?t=" + (new Date()).getTime(), // 加随机数防止缓存
        type: "get",
        dataType: "json",
        success: function (data) {
            // 使用initGeetest接口
            // 参数1：配置参数
            // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "popup", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success, // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                new_captcha: data.new_captcha
            }, handlerPopup);
        }
    });
</script>
</body>
</html>

templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-quiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,intial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">

    <title>Title</title>
    <style>
        * {
            margin: 0;
        }

        .header {
            width: 100%;
            height: 60px;
            background-color: #2aabd2;
        }

        .content {
            width: 80%;
            margin: 20px auto;
        }

        #add {
            margin: 20px auto;
        }
    </style>
</head>
<body>
{% csrf_token %}
<div class="header">
    <span style="font-weight: bold;font-size:30px;margin: 10px">{{ request.user.username }}</span>的个人主页
    <span style="float: right;padding: 20px"><a href="/blog/{{ request.user.username }}"><button>返回个人主页</button></a></span>
</div>
<div class="content">
    <h3>添加文章</h3>

    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="">文章标题</label>
            <div><input type="text" name="title" class="form-control" style="width: 200px">
            </div>
        </div>
        <label for="add">文章内容</label>
            <div>
                <textarea name="article_content" id="add" cols="60" rows="20"></textarea>

            </div>
        <a href="/blog/{{ request.user.username }}"><input id="sub_article" type="submit" class="btn btn-info"></a>
    </form>
</div>

<script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
 <script src="/static/jquery/jquery-3.4.1.js"></script>
<script>


         KindEditor.ready(function(K) {
                window.editor = K.create('#add',{
                    uploadJson:"/upload/",
                    extraFileUploadParams :{
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    filePostName:"upload_img",
                    resizeType:0,
                });
        });
</script>
</body>
</html>

templates/article_detail.html
{% extends 'base.html' %}

{% block page-main %}


    <div class="article-detail">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>

    <div class="poll clearfix">
        <div id="div_digg">
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear" style="clear: both"></div>
            <div class="diggword" id="digg_tips" style="color: red"></div>
        </div>
    </div>
    <!--评论树开始-->
{#    <p>评论树</p>#}
{#    <div class="comment_tree">#}
{##}
{#    </div>#}
{#    <hr>#}
    <!--评论树结束-->

    <!--评论列表开始-->
    <p>评论列表</p>
    <ul class="comment_list list-group">
    {% for comment in comment_list %}
        <li class="list-group-item">
        <div>
            <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;
            <span style="color: grey">{{ comment.create_time|date:"Y-m-d H:i" }}</span>
            <a href=""><span>{{ comment.user.username }}</span></a>
            <a class="pull-right reply_btn" username="{{ comment.user.username }}" comment_pk="{{ comment.pk }}">回复</a>
        </div>
            {% if comment.parent_comment_id %}
                <div class="pid_info " style="background-color: gainsboro">
                  <div>&nbsp;&nbsp;回复：{{ comment.parent_comment.user.username }}&nbsp;&nbsp;&nbsp;&nbsp;{{ comment.parent_comment.content }}</div>
                </div>

                {% endif %}
             <div class="con">
                 <p>
                     {{ comment.content }}&nbsp;&nbsp;
                 </p>

        </div>



        </li>
    {% endfor %}
    </ul>

    <!--评论列表结束-->
    <!-- 评论框开始 -->
    {% if request.user.username %}
        <div class="div_comment">
            <p style="font-weight: bold"><i class="fa fa-commenting" aria-hidden="true"></i>评论内容</p>
            <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
         <p>
            <button id="comment_btn">提交评论</button>
         </p>

        </div>
    {% else %}
        <a href="/login/">登录</a>



    {% endif %}

    <!-- 评论框结束 -->
    {% csrf_token %}

    <div class="info" article_id ="{{ article.pk }}" username="{{ request.user.username }}"></div>


    <script>
    //获取评论数据，展示评论数
        $.ajax({
            url:"/blog/comment_tree/"+"{{ article.pk }}/",
            success:function (data) {
                console.log(data);

                $.each(data,function (index,comment_dict) {
                        var s= '<div class="comment_item div_comment" comment_id='+comment_dict.pk+'><span class="content">'+comment_dict.content+'</span></div>';

                        if(comment_dict.parent_comment_id){
                            //子评论
                            pid = comment_dict.parent_comment_id;
                            $("[comment_id="+pid+"]").append(s);
                        }
                        else {//根评论
                                    $(".comment_tree").append(s);
                        }
                })
            }
        })

        $("#div_digg .action").click(function () {
            if ("{{ request.user.username }}") {
                //点赞或踩灭
                var is_up = $(this).hasClass("diggit");
                console.log(is_up)
                var article_id = "{{ article.pk }}";

                $.ajax({
                    url: "/blog/up_down/",
                    type: "post",
                    data: {
                        is_up: is_up,
                        article_id: article_id,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (data) {
                        console.log(data);
                        if (data.state) {//赞或者灭成功
                            if (is_up) {
                                var val = $("#digg_count").text();
                                val = parseInt(val) + 1;
                                $("#digg_count").text(val);
                            } else {
                                var val = $("#bury_count").text();
                                val = parseInt(val) + 1;
                                $("#bury_count").text(val);
                            }
                        } else {//重复提交
                            if (data.first_action) {
                                $("#digg_tips").html("您已经推荐过了")
                            } else {
                                $("#digg_tips").html("您已经反对过了")
                            }
                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 1000)
                        }
                    }
                })
            } else {
                location.href = '/login/'
            }
        })


    </script>

    <script>
    //提交评论按钮
    var pid = "";

    $('#comment_btn').click(function () {
        var article_id = $(".info").attr("article_id");
        var content = $("#comment_content").val();
        if(pid){
            var index = content.indexOf("\n");
                content = content.slice(index+1)
        }



        $.ajax({
            url:"blog/comment/",
            type:"post",
            data:{
                article_id:article_id,
                    pid:pid,
                content:content,
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
        success:function (data) {
                console.log(data);
                //清空文本，PID
                $("#comment_content").val('')
                pid="";
        }
        })
    })

    //回复按钮事件
    $(".list-group-item .reply_btn").click(function () {

        $("#comment_content").focus();

        var v= "@"+$(this).attr("username")+"\n";
        $("#comment_content").val(v);
        //pid赋值
        pid = $(this).attr("comment_pk")
    })
    </script>

{% endblock %}

templates/article_detail2.html
{% extends 'base.html' %}

{% block page-main %}

    <div class="info" article_id = {{ article.pk }}></div>

    <div class="article-detail">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>

    <div class="poll clearfix">
        <div id="div_digg">
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <div class="buryit action">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear" style="clear: both"></div>
            <div class="diggword" id="digg_tips" style="color: red"></div>
        </div>
    </div>
    <!--评论列表开始-->
    <p>评论列表</p>
    <ul class="comment_list list-group">
    {% for comment in comment_list %}
        <li class="list-group-item">
        <div>
            <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;
            <span style="color: grey">{{ comment.create_time|date:"Y-m-d H:i" }}</span>
            <a href=""><span>{{ comment.user.username }}</span></a>
            <span class="pull-right">回复</span>
        </div>
        <div class="con">
        {{ comment.content }}&nbsp;&nbsp;
        </div>
        </li>
    {% endfor %}
    </ul>

    <!--评论列表结束-->
    <!-- 评论框开始 -->
    {% if request.user.username %}
        <div class="div_comment">
            <p style="font-weight: bold"><i class="fa fa-commenting" aria-hidden="true"></i>评论内容</p>
            <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
         <p>
            <button id="comment_btn">提交评论</button>
         </p>

        </div>
    {% else %}
        <a href="/login/">登录</a>



    {% endif %}

    <!-- 评论框结束 -->
    {% csrf_token %}
    <script>
        $("#div_digg .action").click(function () {
            if ("{{ request.user.username }}") {
                //点赞或踩灭
                var is_up = $(this).hasClass("diggit");
                var article_id = "{{ article.pk }}";

                $.ajax({
                    url: "/blog/up_down/",
                    type: "post",
                    data: {
                        is_up: is_up,
                        article_id: article_id,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (data) {
                        console.log(data);
                        if (data.state) {//赞或者灭成功
                            if (is_up) {
                                var val = $("#digg_count").text();
                                val = parseInt(val) + 1;
                                $("#digg_count").text(val);
                            } else {
                                var val = $("#bury_count").text();
                                val = parseInt(val) + 1;
                                $("#bury_count").text(val);
                            }
                        } else {//重复提交
                            if (data.first_action) {
                                $("#digg_tips").html("您已经推荐过了")
                            } else {
                                $("#digg_tips").html("您已经反对过了")
                            }
                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 1000)
                        }
                    }
                })
            } else {
                location.href = '/login/'
            }
        })


    </script>

    <script>

    $('#comment_btn').click(function () {
        var article_id = $(".info").attr("article_id");
        var content = $("#comment_content").val();
        var pid = "";



        $.ajax({
            url:"blog/comment/",
            type:"post",
            data:{
                article_id:article_id,
                    pid:pid,
                content:content,
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
        success:function (data) {
                console.log(data);

                $("#comment_content").val('')
        }
        })
    })
    </script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-quiv="x-ua-compatible" content="IE=edge">

    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/font/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
    <script src="/static/jquery/jquery-3.4.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <title>{{ blog.title }}</title>
</head>
<body>
<div class="header">
    <p>{{ blog.title }}</p>
    <p style="padding: 30px 10px;float: left"><a href="/index/">MYBLOG</a></p>
</div>
<div class="container">
    {#    左侧广告栏#}
    <div class="col-md-3">
    {% load my_tags %}

    {% get_left_menu username %}
    </div>
    {#    左侧广告栏结束#}

<div class="col-md-8">
{% block page-main %}


{% endblock %}
</div>
</div>

</body>
</html>

templates/left_menu.html
<div class="panel panel-primary">
            <div class="panel-heading">文章标签</div>
            <div class="panel-body">
                {% for category in Category_list %}
                    <p>{{ category.title }}({{ category.c }})</p>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">文章分类</div>
            <div class="panel-body">
                {% for tag in tag_list %}
                    <p>{{ tag.title }}({{ tag.c }})</p>
                {% endfor %}
            </div>
        </div>

      <div class="panel panel-danger">
            <div class="panel-heading">创建时间</div>
            <div class="panel-body">
                {% for archive in archive_list %}
                    <p>{{ archive.archive_ym }}({{ archive.c }})</p>
                {% endfor %}
            </div>
        </div>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-quiv="x-ua-compatible" content="IE=edge">
{#    <meta name="viewport" content="width=device-width,intial-scale=1">#}
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <title>register</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="/reg/" method="post" class="form-horizontal reg-form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group" >
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.re_password }}
                        <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>
                <div class="form-group" >
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                       <div class="form-group">
                    <label class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-8">
                        <label for="id_avatar">
                            <img id="avatar_img" src="/media/avatars/default.jpg" class="L_center_img" alt="">
                        </label>
                        <input type="file"  name="avatar" id="id_avatar" style="display: none">


                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success" id="reg_button">注册</button>
                    </div>
                </div>


            </form>
        </div>
    </div>
</div>


<script src="/static/jquery/jquery-3.4.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
{#通过ajax提交注册数据#}
<script>
    $("#reg_button").click(function () {
    var formData = new FormData();
        formData.append("username",$("#id_username").val() )
        formData.append("password",$("#id_password").val())
        formData.append("re_password",$("#id_re_password").val())
        formData.append("email",$("#id_email").val())
        formData.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val())
        formData.append("avatar",$("#id_avatar")[0].files[0])
    $.ajax({
        url:"/reg/",
        type:"post",
        processData:false,
        contentType:false,
        data:formData,
        success:function(data){

            if (data.status){
            //有错误就展示错误
            //console.log(data.msg);
            //将错误信息填写在页面上
            $.each(data.msg,function(k,v){
                //console.log("id_"+k,v[0]);
                //console.log($("#id_"+k));
                $("#id_"+k).next("span").text(v[0]).parent().parent().addClass("has-error");

            })
        }
        else{
            //没有错误就跳转到指定页面
            location.href = data.msg;
        }

        }
    })
    })
        //将所有input绑定获取讲点额时间，将所有的错误信息清空
    $("form input").focus(function () {
            $(this).next().text("").parent().parent().remove("has-error")
    })

    //给username input框绑定一个失去焦点事件，失去焦点以后就校验用户名是否已经注册
    $("#id_username").blur(function () {
        //用户填写的值
        var username = $(this).val()
        //发请求
        $.ajax({
            url:"/check_username_exist/",
            type:"get",
            data:{"username":username},
            success:function (data) {
                if (data.status){
                    //用户名已经被注册
                    $("#id_username").next().text(data.msg).parent().parent().addClass("has-error");
                }
            }
        })
    })
</script>

{#    找到头像Input ，绑定change事件#}
<script>
    $("#id_avatar").change(function () {
        //读取选中文件
       var fileReader = new FileReader();
       //取到当前选中的头像文件
        console.log(this.files[0]);
        //读取你选中的文件
        fileReader.readAsDataURL(this.files[0]);//读取文件是需要时间的
        fileReader.onload=function()
        {//等上一步读完文件之后，把文件加载到img标签中
        $("#avatar_img").attr("src",fileReader.result);
       };
    })
</script>
</body>
</html>